name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Login to DockerHub Registry
      run: docker login -u $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile -t redseel/tf2:latest
    - name: Publish to Docker Hub
      run: docker push redseel/tf2:latest
