name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: Login to GitHub Packages Docker Registry
          uses: docker/login-action@v1
          with:
            registry: docker.pkg.github.com
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
   # - uses: actions/checkout@v2
   # - name: Build Docker image
   #   run: docker build . --file Dockerfile -t redseel/tf2:latest
   # - name: Publish to Docker Hub
   #   run: docker push redseel/tf2:latest
